'''
Django settings for stridetastic_api project.

Generated by 'django-admin startproject' using Django 5.1.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
'''

import os
from pathlib import Path
from datetime import timedelta

from dotenv import load_dotenv
load_dotenv()


def _env_flag(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"true", "1", "yes", "on"}


def _env_int(name: str, default: int) -> int:
    value = os.getenv(name)
    if value is None:
        return default
    try:
        return int(value)
    except (TypeError, ValueError):
        return default

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a3h32cwvqg!4ot3e8+776n8c1g06nmiz(xjis_0$=yi=#0b$wl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True # if os.getenv('ENVIRONMENT') == 'development' else False

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,').split(',')


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'unfold.contrib.inlines',
    'unfold.contrib.import_export',
    'unfold.contrib.guardian',
    'unfold.contrib.simple_history',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'stridetastic_api',
    'corsheaders',
    'rest_framework',
    'ninja_jwt',
    'ninja_extra',
    'django_celery_beat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'stridetastic_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stridetastic_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

if os.getenv("GITHUB_ACTIONS"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": ":memory:",
        }
    }
    MIGRATION_MODULES = {
        "business_consulting_api": None,
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": "postgres",
            "USER": "postgres",
            "PASSWORD": "postgres",
            "PORT": 5432,
            "HOST": "timescale_stridetastic",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = os.getenv('LANGUAGE_CODE', 'en-us')

TIME_ZONE = os.getenv('TIME_ZONE', 'UTC')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


UNFOLD = {
    "SITE_TITLE": "Administration Panel",
    "SITE_HEADER": "Stridetastic Admin",
    "SITE_URL": "http://localhost:8000/admin/",
    "THEME": "light",
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "sizes": "32x32",
            "type": "image/x-icon",
            "href": "https://cdn.icon-icons.com/icons2/2675/PNG/64/crown_king_queen_icon_161518.png",
        },
    ],
}


CELERY_BROKER_URL = "redis://redis_stridetastic.local:6379/0"
CELERY_RESULT_BACKEND = "redis://redis_stridetastic.local:6379/0"
CELERY_ACCEPT_CONTENT = ["application/json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_IMPORTS = ("stridetastic_api.tasks",)
# Use solo pool (synchronous) to avoid fork() issues with Paho MQTT background threading
# With prefork pool: forked children get zombie background thread that doesn't process PUBACK
# With solo pool: tasks run synchronously in worker process, background thread works normally
CELERY_WORKER_POOL = "solo"
CELERY_TASK_ROUTES = {
    'stridetastic_api.tasks.sniffer_tasks.run_sniffer': {'queue': 'sniffer'},
}

CELERY_BEAT_SCHEDULE = {
    "process_periodic_publish_jobs": {
        "task": "stridetastic_api.tasks.publisher_tasks.process_periodic_publish_jobs",
        "schedule": 30.0,
    }
}

# Periodic background snapshot of high-level network overview metrics
CELERY_BEAT_SCHEDULE["record_network_overview_snapshot"] = {
    "task": "stridetastic_api.tasks.metrics_tasks.record_network_overview_snapshot",
    "schedule": 60.0,
}

# Reachability configuration: nodes are considered reachable if seen within this timeout
REACTIVE_REACHABILITY_TIMEOUT_SECS = _env_int("REACTIVE_REACHABILITY_TIMEOUT_SECS", 3600)
# How often Celery beat should run the unreachable marker task (seconds)
REACTIVE_REACHABILITY_CHECK_INTERVAL_SECS = _env_int(
    "REACTIVE_REACHABILITY_CHECK_INTERVAL_SECS", 60
)

# Celery Beat job to mark nodes unreachable when not seen within timeout
CELERY_BEAT_SCHEDULE["mark_unreachable_nodes"] = {
    "task": "stridetastic_api.tasks.metrics_tasks.mark_unreachable_nodes",
    "schedule": REACTIVE_REACHABILITY_CHECK_INTERVAL_SECS,
}


SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_SECURE = False #if ENVIRONMENT == "development" else True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_AGE = 1209600
SESSION_EXPIRE_AT_BROWSER_CLOSE = False


CSRF_COOKIE_SECURE = False #if ENVIRONMENT == "development" else True
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = "Lax"
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:8000",
]


CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]


NINJA_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "AUTH_HEADER_TYPES": ("Bearer",),
}


CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": "redis://redis_stridetastic.local:6379/1",
    }
}


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} - {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'stridetastic_api': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

MQTT_BROKER_ADDRESS = os.getenv("MQTT_BROKER_ADDRESS", "mqtt.meshtastic.org")
MQTT_BROKER_PORT = int(os.getenv("MQTT_BROKER_PORT", 1883))
MQTT_TOPIC = os.getenv("MQTT_TOPIC", "msh/US/2/e/#")
MQTT_USERNAME = os.getenv("MQTT_USERNAME", "meshdev")
MQTT_PASSWORD = os.getenv("MQTT_PASSWORD", "large4cats")
MQTT_TLS = os.getenv("MQTT_TLS", "false").lower() == "true"
MQTT_CA_CERTS = os.getenv("MQTT_CA_CERTS", None)
MQTT_BASE_TOPIC = os.getenv("MQTT_BASE_TOPIC", "msh/US/2/e")

SERIAL_PORT = os.getenv("SERIAL_PORT", "/dev/ttyUSB0")
SERIAL_BAUDRATE = int(os.getenv("SERIAL_BAUDRATE", "921600"))

SET_VIRTUAL_NODES = _env_flag("SET_VIRTUAL_NODES", True)

DEFAULT_VIRTUAL_NODE_ENABLED = _env_flag("DEFAULT_VIRTUAL_NODE_ENABLED", True)
DEFAULT_VIRTUAL_NODE_ID = ((os.getenv("DEFAULT_VIRTUAL_NODE_ID") or "!deafbeef").strip() or "!deafbeef")
DEFAULT_VIRTUAL_NODE_SHORT_NAME = (os.getenv("DEFAULT_VIRTUAL_NODE_SHORT_NAME") or "VRT").strip()
DEFAULT_VIRTUAL_NODE_LONG_NAME = (os.getenv("DEFAULT_VIRTUAL_NODE_LONG_NAME") or "Stridetastic Virtual Node").strip()
DEFAULT_VIRTUAL_NODE_ROLE = (((os.getenv("DEFAULT_VIRTUAL_NODE_ROLE") or "CLIENT").strip() or "CLIENT").upper())
DEFAULT_VIRTUAL_NODE_HW_MODEL = (((os.getenv("DEFAULT_VIRTUAL_NODE_HW_MODEL") or "UNSET").strip() or "UNSET").upper())
DEFAULT_VIRTUAL_NODE_IS_LICENSED = _env_flag("DEFAULT_VIRTUAL_NODE_IS_LICENSED", False)
DEFAULT_VIRTUAL_NODE_IS_UNMESSAGABLE = _env_flag("DEFAULT_VIRTUAL_NODE_IS_UNMESSAGABLE", False)
DEFAULT_VIRTUAL_NODE_PUBLIC_KEY = (os.getenv("DEFAULT_VIRTUAL_NODE_PUBLIC_KEY") or "").strip() or None
DEFAULT_VIRTUAL_NODE_PRIVATE_KEY = (os.getenv("DEFAULT_VIRTUAL_NODE_PRIVATE_KEY") or "").strip() or None


CAPTURE_MAX_FILESIZE = _env_int("CAPTURE_MAX_FILESIZE", 1_073_741_824)
CAPTURE_TASK_TIMEOUT = _env_int("CAPTURE_TASK_TIMEOUT", 15)
